language: node_js

node_js:
  - '24'

env:
  - TRAVIS=true

addons:
  chrome: stable

before_install:
  - "corepack enable"

before_script:
  - "pnpm install"
  - "pnpm build"

script:
  - "pnpm test"
